### ISSUE TITLE
2+ participants and double elimination

### ISSUE THREAD

**Issue by psc2350** [krimpedance/KRTournamentView#1]
How do I do a 2+ participants game such as mahjong, and be able to choose how many winner goes to next round. For example, to have 2 winner from each mahjong table to win and the rest goes to the looser group.

**Comment by krimpedance** [comment]
@psc2350 
This library can't do such thing now.
( But there is a plan. )

**Comment by krimpedance** [comment]
@psc2350 
Try `dev` branch. (I have not cleaned up yet)
